name = "blackpill_v12_a0b_playground"
description = ""
version = "0.1.0-dev"

authors = ["Artem Paraev"]
maintainers = ["Artem Paraev <artemparaev.dev@gmail.com>"]
maintainers-logins = ["iharuspex"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["blackpill_v12_a0b_playground"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[configuration.values]
light_blackpill_stm32f401.stm32f401 = "CC"

[[depends-on]]
gnat_arm_elf = "*"
a0b_base = "*"
a0b_time = "*"
a0b_stm32f401_gpio = "*"
a0b_armv7m_systick_clock = "*"
a0b_i2c = "*"
a0b_stm32f401_i2c = "*"
a0b_stm32f401_dma = "*"
light_blackpill_stm32f401 = "*"
